package com.ihmhny.freemarker.model;

import com.ihmhny.freemarker.utils.GenerateNeedMap;
import com.ihmhny.freemarker.utils.PropUtils;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 需要生成的表名和类名之间的对应关系
 *
 * @author Xiaobei
 * @create 2017-06-24 16:36
 */
public class TableNeededMap {

    /**
     * 表名与类名之间对应关系的map集合
     */
    public static Map<String,String> needTablesMap = new HashMap<>();

    public static Map<String,String> moduleMap = new HashMap<>();

    public static Map<String,String> requestMappingMap = new HashMap<>();


    /**
     * 表名的集合
     */
    public static List<String> needTablesList = new ArrayList<>();

    static {
//        needTablesMap.put("account_binding_mapping", "BindingMapping");
//        needTablesMap.put("after_sale_arbitration", "SaleArbitration");
//        needTablesMap.put("after_sale_attachment", "SaleAttachment");
//        needTablesMap.put("after_sale_audit", "SaleAudit");
//        needTablesMap.put("after_sale_complaint", "SaleComplaint");
//        needTablesMap.put("after_sale_evaluation", "SaleEvaluation");
//        needTablesMap.put("after_sale_refund", "SaleRefund");
//        needTablesMap.put("after_sale_refund_item", "SaleRefundItem");
//        needTablesMap.put("after_sale_score_count", "SaleScoreCount");
//        needTablesMap.put("after_sale_service", "SaleService");
//        needTablesMap.put("b2b_download_task", "DownloadTask");
//        needTablesMap.put("b2b_edition", "Edition");
//        needTablesMap.put("b2b_function", "Function");
//        needTablesMap.put("b2b_jsfparam", "Jsfparam");
//        needTablesMap.put("b2b_market_channel", "MarketChannel");
//        needTablesMap.put("b2b_module", "Module");
//        needTablesMap.put("base_flow", "Flow");
//        needTablesMap.put("base_msg_record", "MsgRecord");
//        needTablesMap.put("base_sms_config", "SmsConfig");
//        needTablesMap.put("base_user_favorite_item", "UserFavoriteItem");
//        needTablesMap.put("base_user_favorite_shop", "UserFavoriteShop");
//        needTablesMap.put("base_website_message", "WebsiteMessage");
//        needTablesMap.put("comment_black_list", "BlackList");
//        needTablesMap.put("comment_buyer_score_statistical", "BuyerScoreStatistical");
//        needTablesMap.put("comment_buyer_to_goods", "BuyerToGoods");
//        needTablesMap.put("comment_buyer_to_shop", "BuyerToShop");
//        needTablesMap.put("comment_goods_score_statistical", "GoodsScoreStatistical");
//        needTablesMap.put("comment_reply", "Reply");
//        needTablesMap.put("comment_shop_score_statistical", "ShopScoreStatistical");
//        needTablesMap.put("comment_shop_to_buyer", "ShopToBuyer");
//        needTablesMap.put("comment_version", "Version");
//        needTablesMap.put("commission_every_pay_record", "EveryPayRecord");
//        needTablesMap.put("commission_shop", "Shop");
//        needTablesMap.put("commission_shop_category_des", "ShopCategoryDes");
//        needTablesMap.put("coupon", "coupon");
//        needTablesMap.put("coupon_rule", "Rule");
//        needTablesMap.put("coupon_use", "Use");
//        needTablesMap.put("customized_discount", "Discount");
//        needTablesMap.put("customized_discount_item", "DiscountItem");
//        needTablesMap.put("customized_extend_orders", "ExtendOrders");
//        needTablesMap.put("customized_page", "Page");
//        needTablesMap.put("customized_pay_config", "PayConfig");
//        needTablesMap.put("customized_promotion", "Promotion");
//        needTablesMap.put("delivery_addressbase", "Addressbase");
//        needTablesMap.put("delivery_company_base", "CompanyBase");
//        needTablesMap.put("delivery_company_toshop", "CompanyToshop");
//        needTablesMap.put("delivery_express_company", "ExpressCompany");
//        needTablesMap.put("delivery_fee_info", "FeeInfo");
//        needTablesMap.put("delivery_fee_template", "FeeTemplate");
//        needTablesMap.put("delivery_fee_template_detail", "FeeTemplateDetail");
//        needTablesMap.put("delivery_info", "Info");
//        needTablesMap.put("delivery_range", "Range");
//        needTablesMap.put("delivery_shop_mapping", "ShopMapping");
//        needTablesMap.put("delivery_status", "Status");
//        needTablesMap.put("delivery_useful_address_info", "UsefulAddressInfo");
//        needTablesMap.put("design_pattern", "Pattern");
//        needTablesMap.put("distribute_order_interface", "OrderInterface");
//        needTablesMap.put("ecc_plt_ol_site_d", "PltOlSiteD");
//        needTablesMap.put("ecc_plt_ol_site_page_d", "PltOlSitePageD");
//        needTablesMap.put("ecc_plt_ol_site_page_top10_d", "PltOlSitePageTop10D");
//        needTablesMap.put("ecc_plt_ol_usertype_d", "PltOlUsertypeD");
//        needTablesMap.put("ecc_shop_ol_site_d", "ShopOlSiteD");
//        needTablesMap.put("ecc_shop_page_ol_site_d", "ShopPageOlSiteD");
//        needTablesMap.put("edition_func", "Func");
//        needTablesMap.put("field_certification", "Certification");
//        needTablesMap.put("field_certification_attachment", "CertificationAttachment");
//        needTablesMap.put("finance_withdraw_apply", "WithdrawApply");
//        needTablesMap.put("finance_withdraw_record", "WithdrawRecord");
//        needTablesMap.put("groupon_info", "Info");
//        needTablesMap.put("groupon_order", "Order");
//        needTablesMap.put("groupon_rule", "Rule");
//        needTablesMap.put("item", "item");
//        needTablesMap.put("item_attr", "Attr");
//        needTablesMap.put("item_attr_formula", "AttrFormula");
//        needTablesMap.put("item_attr_value", "AttrValue");
//        needTablesMap.put("item_attribute", "Attribute");
//        needTablesMap.put("item_attribute_value", "AttributeValue");
//        needTablesMap.put("item_brand", "Brand");
//        needTablesMap.put("item_buyer_extends_info", "BuyerExtendsInfo");
//        needTablesMap.put("item_category", "Category");
//        needTablesMap.put("item_category_attr", "CategoryAttr");
//        needTablesMap.put("item_category_attr_value", "CategoryAttrValue");
//        needTablesMap.put("item_category_bak", "CategoryBak");
//        needTablesMap.put("item_category_brand", "CategoryBrand");
//        needTablesMap.put("item_customized_sku", "CustomizedSku");
//        needTablesMap.put("item_delivery_info", "DeliveryInfo");
//        needTablesMap.put("item_picpdf", "Picpdf");
//        needTablesMap.put("item_picture", "Picture");
//        needTablesMap.put("item_price", "Price");
//        needTablesMap.put("item_sku", "Sku");
//        needTablesMap.put("item_sku_picture", "SkuPicture");
//        needTablesMap.put("jc_user_info", "UserInfo");
//        needTablesMap.put("mall_ad_count", "AdCount");
//        needTablesMap.put("mall_advertise", "Advertise");
//        needTablesMap.put("mall_banner", "Banner");
//        needTablesMap.put("mall_domain_info", "DomainInfo");
//        needTablesMap.put("mall_help_classify", "HelpClassify");
//        needTablesMap.put("mall_help_document", "HelpDocument");
//        needTablesMap.put("mall_info", "Info");
//        needTablesMap.put("mall_mobile_instance_module", "MobileInstanceModule");
//        needTablesMap.put("mall_mobile_instance_template", "MobileInstanceTemplate");
//        needTablesMap.put("mall_mobile_publish_template", "MobilePublishTemplate");
//        needTablesMap.put("mall_notice", "Notice");
//        needTablesMap.put("mall_recommend", "Recommend");
//        needTablesMap.put("mall_recommend_attr", "RecommendAttr");
//        needTablesMap.put("mall_tdk", "Tdk");
//        needTablesMap.put("mall_user_feedback", "UserFeedback");
//        needTablesMap.put("menu_group", "Group");
//        needTablesMap.put("menu_resource", "Resource");
//        needTablesMap.put("menu_resource_cancel", "ResourceCancel");
//        needTablesMap.put("menu_resource_template", "ResourceTemplate");
//        needTablesMap.put("mobile_page_config", "PageConfig");
//        needTablesMap.put("package_orders", "Orders");
//        needTablesMap.put("payment_deal", "Deal");
//        needTablesMap.put("payment_detail", "Detail");
//        needTablesMap.put("payment_mapping", "Mapping");
//        needTablesMap.put("plat_account_period_rule", "AccountPeriodRule");
//        needTablesMap.put("platform_activity", "Activity");
//        needTablesMap.put("platform_ad", "Ad");
//        needTablesMap.put("platform_company_info", "CompanyInfo");
//        needTablesMap.put("platform_customer_service", "CustomerService");
//        needTablesMap.put("platform_edition", "Edition");
//        needTablesMap.put("platform_financial_apply", "FinancialApply");
//        needTablesMap.put("platform_financial_apply__data", "FinancialApplyData");
//        needTablesMap.put("platform_financial_cooperation", "FinancialCooperation");
//        needTablesMap.put("platform_financial_picture", "FinancialPicture");
//        needTablesMap.put("platform_financial_products", "FinancialProducts");
//        needTablesMap.put("platform_financial_region", "FinancialRegion");
//        needTablesMap.put("platform_front_category", "FrontCategory");
//        needTablesMap.put("platform_front_category_mapping", "FrontCategoryMapping");
//        needTablesMap.put("platform_front_editcategory", "FrontEditcategory");
//        needTablesMap.put("platform_func", "Func");
//        needTablesMap.put("platform_hotword", "Hotword");
//        needTablesMap.put("platform_item", "Item");
//        needTablesMap.put("platform_item_handbook", "ItemHandbook");
//        needTablesMap.put("platform_item_picture", "ItemPicture");
//        needTablesMap.put("platform_item_sku", "ItemSku");
//        needTablesMap.put("platform_item_sku_picture", "ItemSkuPicture");
//        needTablesMap.put("platform_menu_group_func", "MenuGroupFunc");
//        needTablesMap.put("platform_menu_link", "MenuLink");
//        needTablesMap.put("platform_recommend_record", "RecommendRecord");
//        needTablesMap.put("platform_service_rule", "ServiceRule");
//        needTablesMap.put("platform_user_blacklist", "UserBlacklist");
//        needTablesMap.put("promotion_full_reduction", "FullReduction");
//        needTablesMap.put("promotion_info", "Info");
//        needTablesMap.put("promotion_markdown", "Markdown");
//        needTablesMap.put("promotion_platform", "Platform");
//        needTablesMap.put("promotion_platform_category", "PlatformCategory");
//        needTablesMap.put("properties_config", "Config");
//        needTablesMap.put("properties_config_bak", "ConfigBak");
//        needTablesMap.put("properties_template", "Template");
//        needTablesMap.put("properties_template_bak", "TemplateBak");
//        needTablesMap.put("purchase_order", "Order");
//        needTablesMap.put("purchase_order_audit", "OrderAudit");
//        needTablesMap.put("purchase_product", "Product");
//        needTablesMap.put("purchase_quotation_audit", "QuotationAudit");
//        needTablesMap.put("purchase_quote_product", "QuoteProduct");
//        needTablesMap.put("purchase_quote_shop", "QuoteShop");
//        needTablesMap.put("purchase_vendor", "Vendor");
//        needTablesMap.put("purchase_vendor_invitation", "VendorInvitation");
//        needTablesMap.put("ran_username", "Username");
//        needTablesMap.put("settlement", "settlement");
//        needTablesMap.put("settlement_category_expense", "CategoryExpense");
//        needTablesMap.put("settlement_detail", "Detail");
//        needTablesMap.put("shop_address", "Address");
//        needTablesMap.put("shop_address_copy", "AddressCopy");
//        needTablesMap.put("shop_banner", "Banner");
//        needTablesMap.put("shop_banner_publish", "BannerPublish");
//        needTablesMap.put("shop_base_layout", "BaseLayout");
//        needTablesMap.put("shop_base_module", "BaseModule");
//        needTablesMap.put("shop_brand", "Brand");
//        needTablesMap.put("shop_category_seller", "CategorySeller");
//        needTablesMap.put("shop_credit_audit", "CreditAudit");
//        needTablesMap.put("shop_credit_constant_config", "CreditConstantConfig");
//        needTablesMap.put("shop_customer_service", "CustomerService");
//        needTablesMap.put("shop_distribution_item_sku", "DistributionItemSku");
//        needTablesMap.put("shop_distributor", "Distributor");
//        needTablesMap.put("shop_distributor_rel", "DistributorRel");
//        needTablesMap.put("shop_domain_mapper", "DomainMapper");
//        needTablesMap.put("shop_fare", "Fare");
//        needTablesMap.put("shop_info", "Info");
//        needTablesMap.put("shop_info_extends", "InfoExtends");
//        needTablesMap.put("shop_info_for_query", "InfoForQuery");
//        needTablesMap.put("shop_info_snapshot", "InfoSnapshot");
//        needTablesMap.put("shop_instance_layout", "InstanceLayout");
//        needTablesMap.put("shop_instance_module", "InstanceModule");
//        needTablesMap.put("shop_instance_module_extend", "InstanceModuleExtend");
//        needTablesMap.put("shop_instance_page", "InstancePage");
//        needTablesMap.put("shop_instance_template", "InstanceTemplate");
//        needTablesMap.put("shop_item_special_rule", "ItemSpecialRule");
//        needTablesMap.put("shop_member", "Member");
//        needTablesMap.put("shop_member_group", "MemberGroup");
//        needTablesMap.put("shop_member_group_price", "MemberGroupPrice");
//        needTablesMap.put("shop_member_rule", "MemberRule");
//        needTablesMap.put("shop_platform_category", "PlatformCategory");
//        needTablesMap.put("shop_publish_layout", "PublishLayout");
//        needTablesMap.put("shop_publish_module", "PublishModule");
//        needTablesMap.put("shop_publish_module_extend", "PublishModuleExtend");
//        needTablesMap.put("shop_publish_page", "PublishPage");
//        needTablesMap.put("shop_publish_template", "PublishTemplate");
//        needTablesMap.put("shop_regedit_credit", "RegeditCredit");
//        needTablesMap.put("shop_rule", "Rule");
//        needTablesMap.put("shop_sale_template", "SaleTemplate");
//        needTablesMap.put("shop_service_rule", "ServiceRule");
//        needTablesMap.put("shop_template", "Template");
//        needTablesMap.put("shop_template_layout", "TemplateLayout");
//        needTablesMap.put("shop_template_module", "TemplateModule");
//        needTablesMap.put("shop_template_page", "TemplatePage");
//        needTablesMap.put("shop_user_check_book", "UserCheckBook");
//        needTablesMap.put("shop_user_check_delay", "UserCheckDelay");
//        needTablesMap.put("shop_user_credit_account", "UserCreditAccount");
//        needTablesMap.put("shop_user_credit_account_history", "UserCreditAccountHistory");
//        needTablesMap.put("shop_user_credit_check", "UserCreditCheck");
//        needTablesMap.put("shop_user_credit_check_batch", "UserCreditCheckBatch");
//        needTablesMap.put("sms_platform_config", "PlatformConfig");
//        needTablesMap.put("sms_task", "Task");
//        needTablesMap.put("sms_template", "Template");
//        needTablesMap.put("special_aptitude", "Aptitude");
//        needTablesMap.put("task", "task");
//        needTablesMap.put("tenant_business_info", "BusinessInfo");
//        needTablesMap.put("tenant_order", "Order");
//        needTablesMap.put("tenant_refund", "Refund");
//        needTablesMap.put("trade_instead_payment", "InsteadPayment");
//        needTablesMap.put("trade_inventory", "Inventory");
//        needTablesMap.put("trade_inventory_operation_log", "InventoryOperationLog");
//        needTablesMap.put("trade_invoice", "Invoice");
//        needTablesMap.put("trade_order_extends_state", "OrderExtendsState");
//        needTablesMap.put("trade_order_items", "OrderItems");
//        needTablesMap.put("trade_order_items_price_history", "OrderItemsPriceHistory");
//        needTablesMap.put("trade_order_price_history", "OrderPriceHistory");
//        needTablesMap.put("trade_orders", "Orders");
//        needTablesMap.put("trade_payment_type", "PaymentType");
//        needTablesMap.put("trade_payment_type_attribute", "PaymentTypeAttribute");
//        needTablesMap.put("trade_sku_price", "SkuPrice");
//        needTablesMap.put("trade_sku_price_log", "SkuPriceLog");
        needTablesMap.put("urp_depart", "Depart");
        needTablesMap.put("urp_menu", "Menu");
        needTablesMap.put("urp_menu_group_r", "MenuGroupR");
        needTablesMap.put("urp_menugroup", "Menugroup");
        needTablesMap.put("urp_user", "User");
        needTablesMap.put("urp_user_group_r", "UserGroupR");
        needTablesMap.put("urp_user_menu_r", "UserMenuR");
        needTablesMap.put("urp_usergroup", "Usergroup");
//        needTablesMap.put("user", "user");
//        needTablesMap.put("user_audit", "Audit");
//        needTablesMap.put("user_buyer_company_info_device_ky", "BuyerCompanyInfoDeviceKy");
//        needTablesMap.put("user_buyer_company_info_ky", "BuyerCompanyInfoKy");
//        needTablesMap.put("user_category", "Category");
//        needTablesMap.put("user_contract", "Contract");
//        needTablesMap.put("user_contract_audit", "ContractAudit");
//        needTablesMap.put("user_extends", "Extends");
//        needTablesMap.put("user_mall_resource", "MallResource");
//        needTablesMap.put("user_mall_resource_template", "MallResourceTemplate");
//        needTablesMap.put("user_modify_detail", "ModifyDetail");
//        needTablesMap.put("user_modify_info", "ModifyInfo");
//        needTablesMap.put("user_permission", "Permission");
//        needTablesMap.put("user_permission_code", "PermissionCode");
//        needTablesMap.put("user_permission_code_template", "PermissionCodeTemplate");
//        needTablesMap.put("user_platform_menu", "PlatformMenu");
//        needTablesMap.put("user_properties", "Properties");
//        needTablesMap.put("user_role", "Role");
        //===============================================//
        needTablesList.add("account_binding_mapping");
        needTablesList.add("after_sale_arbitration");
        needTablesList.add("after_sale_attachment");
        needTablesList.add("after_sale_audit");
        needTablesList.add("after_sale_complaint");
        needTablesList.add("after_sale_evaluation");
        needTablesList.add("after_sale_refund");
        needTablesList.add("after_sale_refund_item");
        needTablesList.add("after_sale_score_count");
        needTablesList.add("after_sale_service");
        needTablesList.add("b2b_download_task");
        needTablesList.add("b2b_edition");
        needTablesList.add("b2b_function");
        needTablesList.add("b2b_jsfparam");
        needTablesList.add("b2b_market_channel");
        needTablesList.add("b2b_module");
        needTablesList.add("base_flow");
        needTablesList.add("base_msg_record");
        needTablesList.add("base_sms_config");
        needTablesList.add("base_user_favorite_item");
        needTablesList.add("base_user_favorite_shop");
        needTablesList.add("base_website_message");
        needTablesList.add("comment_black_list");
        needTablesList.add("comment_buyer_score_statistical");
        needTablesList.add("comment_buyer_to_goods");
        needTablesList.add("comment_buyer_to_shop");
        needTablesList.add("comment_goods_score_statistical");
        needTablesList.add("comment_reply");
        needTablesList.add("comment_shop_score_statistical");
        needTablesList.add("comment_shop_to_buyer");
        needTablesList.add("comment_version");
        needTablesList.add("commission_every_pay_record");
        needTablesList.add("commission_shop");
        needTablesList.add("commission_shop_category_des");
        needTablesList.add("coupon");
        needTablesList.add("coupon_rule");
        needTablesList.add("coupon_use");
        needTablesList.add("customized_discount");
        needTablesList.add("customized_discount_item");
        needTablesList.add("customized_extend_orders");
        needTablesList.add("customized_page");
        needTablesList.add("customized_pay_config");
        needTablesList.add("customized_promotion");
        needTablesList.add("delivery_addressbase");
        needTablesList.add("delivery_company_base");
        needTablesList.add("delivery_company_toshop");
        needTablesList.add("delivery_express_company");
        needTablesList.add("delivery_fee_info");
        needTablesList.add("delivery_fee_template");
        needTablesList.add("delivery_fee_template_detail");
        needTablesList.add("delivery_info");
        needTablesList.add("delivery_range");
        needTablesList.add("delivery_shop_mapping");
        needTablesList.add("delivery_status");
        needTablesList.add("delivery_useful_address_info");
        needTablesList.add("design_pattern");
        needTablesList.add("distribute_order_interface");
        needTablesList.add("ecc_plt_ol_site_d");
        needTablesList.add("ecc_plt_ol_site_page_d");
        needTablesList.add("ecc_plt_ol_site_page_top10_d");
        needTablesList.add("ecc_plt_ol_usertype_d");
        needTablesList.add("ecc_shop_ol_site_d");
        needTablesList.add("ecc_shop_page_ol_site_d");
        needTablesList.add("edition_func");
        needTablesList.add("field_certification");
        needTablesList.add("field_certification_attachment");
        needTablesList.add("finance_withdraw_apply");
        needTablesList.add("finance_withdraw_record");
        needTablesList.add("groupon_info");
        needTablesList.add("groupon_order");
        needTablesList.add("groupon_rule");
        needTablesList.add("item");
        needTablesList.add("item_attr");
        needTablesList.add("item_attr_formula");
        needTablesList.add("item_attr_value");
        needTablesList.add("item_attribute");
        needTablesList.add("item_attribute_value");
        needTablesList.add("item_brand");
        needTablesList.add("item_buyer_extends_info");
        needTablesList.add("item_category");
        needTablesList.add("item_category_attr");
        needTablesList.add("item_category_attr_value");
        needTablesList.add("item_category_bak");
        needTablesList.add("item_category_brand");
        needTablesList.add("item_customized_sku");
        needTablesList.add("item_delivery_info");
        needTablesList.add("item_picpdf");
        needTablesList.add("item_picture");
        needTablesList.add("item_price");
        needTablesList.add("item_sku");
        needTablesList.add("item_sku_picture");
        needTablesList.add("jc_user_info");
        needTablesList.add("mall_ad_count");
        needTablesList.add("mall_advertise");
        needTablesList.add("mall_banner");
        needTablesList.add("mall_domain_info");
        needTablesList.add("mall_help_classify");
        needTablesList.add("mall_help_document");
        needTablesList.add("mall_info");
        needTablesList.add("mall_mobile_instance_module");
        needTablesList.add("mall_mobile_instance_template");
        needTablesList.add("mall_mobile_publish_template");
        needTablesList.add("mall_notice");
        needTablesList.add("mall_recommend");
        needTablesList.add("mall_recommend_attr");
        needTablesList.add("mall_tdk");
        needTablesList.add("mall_user_feedback");
        needTablesList.add("menu_group");
        needTablesList.add("menu_resource");
        needTablesList.add("menu_resource_cancel");
        needTablesList.add("menu_resource_template");
        needTablesList.add("mobile_page_config");
        needTablesList.add("package_orders");
        needTablesList.add("payment_deal");
        needTablesList.add("payment_detail");
        needTablesList.add("payment_mapping");
        needTablesList.add("plat_account_period_rule");
        needTablesList.add("platform_activity");
        needTablesList.add("platform_ad");
        needTablesList.add("platform_company_info");
        needTablesList.add("platform_customer_service");
        needTablesList.add("platform_edition");
        needTablesList.add("platform_financial_apply");
        needTablesList.add("platform_financial_apply__data");
        needTablesList.add("platform_financial_cooperation");
        needTablesList.add("platform_financial_picture");
        needTablesList.add("platform_financial_products");
        needTablesList.add("platform_financial_region");
        needTablesList.add("platform_front_category");
        needTablesList.add("platform_front_category_mapping");
        needTablesList.add("platform_front_editcategory");
        needTablesList.add("platform_func");
        needTablesList.add("platform_hotword");
        needTablesList.add("platform_item");
        needTablesList.add("platform_item_handbook");
        needTablesList.add("platform_item_picture");
        needTablesList.add("platform_item_sku");
        needTablesList.add("platform_item_sku_picture");
        needTablesList.add("platform_menu_group_func");
        needTablesList.add("platform_menu_link");
        needTablesList.add("platform_recommend_record");
        needTablesList.add("platform_service_rule");
        needTablesList.add("platform_user_blacklist");
        needTablesList.add("promotion_full_reduction");
        needTablesList.add("promotion_info");
        needTablesList.add("promotion_markdown");
        needTablesList.add("promotion_platform");
        needTablesList.add("promotion_platform_category");
        needTablesList.add("properties_config");
        needTablesList.add("properties_config_bak");
        needTablesList.add("properties_template");
        needTablesList.add("properties_template_bak");
        needTablesList.add("purchase_order");
        needTablesList.add("purchase_order_audit");
        needTablesList.add("purchase_product");
        needTablesList.add("purchase_quotation_audit");
        needTablesList.add("purchase_quote_product");
        needTablesList.add("purchase_quote_shop");
        needTablesList.add("purchase_vendor");
        needTablesList.add("purchase_vendor_invitation");
        needTablesList.add("ran_username");
        needTablesList.add("settlement");
        needTablesList.add("settlement_category_expense");
        needTablesList.add("settlement_detail");
        needTablesList.add("shop_address");
        needTablesList.add("shop_address_copy");
        needTablesList.add("shop_banner");
        needTablesList.add("shop_banner_publish");
        needTablesList.add("shop_base_layout");
        needTablesList.add("shop_base_module");
        needTablesList.add("shop_brand");
        needTablesList.add("shop_category_seller");
        needTablesList.add("shop_credit_audit");
        needTablesList.add("shop_credit_constant_config");
        needTablesList.add("shop_customer_service");
        needTablesList.add("shop_distribution_item_sku");
        needTablesList.add("shop_distributor");
        needTablesList.add("shop_distributor_rel");
        needTablesList.add("shop_domain_mapper");
        needTablesList.add("shop_fare");
        needTablesList.add("shop_info");
        needTablesList.add("shop_info_extends");
        needTablesList.add("shop_info_for_query");
        needTablesList.add("shop_info_snapshot");
        needTablesList.add("shop_instance_layout");
        needTablesList.add("shop_instance_module");
        needTablesList.add("shop_instance_module_extend");
        needTablesList.add("shop_instance_page");
        needTablesList.add("shop_instance_template");
        needTablesList.add("shop_item_special_rule");
        needTablesList.add("shop_member");
        needTablesList.add("shop_member_group");
        needTablesList.add("shop_member_group_price");
        needTablesList.add("shop_member_rule");
        needTablesList.add("shop_platform_category");
        needTablesList.add("shop_publish_layout");
        needTablesList.add("shop_publish_module");
        needTablesList.add("shop_publish_module_extend");
        needTablesList.add("shop_publish_page");
        needTablesList.add("shop_publish_template");
        needTablesList.add("shop_regedit_credit");
        needTablesList.add("shop_rule");
        needTablesList.add("shop_sale_template");
        needTablesList.add("shop_service_rule");
        needTablesList.add("shop_template");
        needTablesList.add("shop_template_layout");
        needTablesList.add("shop_template_module");
        needTablesList.add("shop_template_page");
        needTablesList.add("shop_user_check_book");
        needTablesList.add("shop_user_check_delay");
        needTablesList.add("shop_user_credit_account");
        needTablesList.add("shop_user_credit_account_history");
        needTablesList.add("shop_user_credit_check");
        needTablesList.add("shop_user_credit_check_batch");
        needTablesList.add("sms_platform_config");
        needTablesList.add("sms_task");
        needTablesList.add("sms_template");
        needTablesList.add("special_aptitude");
        needTablesList.add("task");
        needTablesList.add("tenant_business_info");
        needTablesList.add("tenant_order");
        needTablesList.add("tenant_refund");
        needTablesList.add("trade_instead_payment");
        needTablesList.add("trade_inventory");
        needTablesList.add("trade_inventory_operation_log");
        needTablesList.add("trade_invoice");
        needTablesList.add("trade_order_extends_state");
        needTablesList.add("trade_order_items");
        needTablesList.add("trade_order_items_price_history");
        needTablesList.add("trade_order_price_history");
        needTablesList.add("trade_orders");
        needTablesList.add("trade_payment_type");
        needTablesList.add("trade_payment_type_attribute");
        needTablesList.add("trade_sku_price");
        needTablesList.add("trade_sku_price_log");
        needTablesList.add("urp_depart");
        needTablesList.add("urp_menu");
        needTablesList.add("urp_menu_group_r");
        needTablesList.add("urp_menugroup");
        needTablesList.add("urp_user");
        needTablesList.add("urp_user_group_r");
        needTablesList.add("urp_user_menu_r");
        needTablesList.add("urp_usergroup");
        needTablesList.add("user");
        needTablesList.add("user_audit");
        needTablesList.add("user_buyer_company_info_device_ky");
        needTablesList.add("user_buyer_company_info_ky");
        needTablesList.add("user_category");
        needTablesList.add("user_contract");
        needTablesList.add("user_contract_audit");
        needTablesList.add("user_extends");
        needTablesList.add("user_mall_resource");
        needTablesList.add("user_mall_resource_template");
        needTablesList.add("user_modify_detail");
        needTablesList.add("user_modify_info");
        needTablesList.add("user_permission");
        needTablesList.add("user_permission_code");
        needTablesList.add("user_permission_code_template");
        needTablesList.add("user_platform_menu");
        needTablesList.add("user_properties");
        needTablesList.add("user_role");
        //===============================================//
        moduleMap.put("account_binding_mapping", "account");
        moduleMap.put("after_sale_arbitration", "after");
        moduleMap.put("after_sale_attachment", "after");
        moduleMap.put("after_sale_audit", "after");
        moduleMap.put("after_sale_complaint", "after");
        moduleMap.put("after_sale_evaluation", "after");
        moduleMap.put("after_sale_refund", "after");
        moduleMap.put("after_sale_refund_item", "after");
        moduleMap.put("after_sale_score_count", "after");
        moduleMap.put("after_sale_service", "after");
        moduleMap.put("b2b_download_task", "b2b");
        moduleMap.put("b2b_edition", "b2b");
        moduleMap.put("b2b_function", "b2b");
        moduleMap.put("b2b_jsfparam", "b2b");
        moduleMap.put("b2b_market_channel", "b2b");
        moduleMap.put("b2b_module", "b2b");
        moduleMap.put("base_flow", "base");
        moduleMap.put("base_msg_record", "base");
        moduleMap.put("base_sms_config", "base");
        moduleMap.put("base_user_favorite_item", "base");
        moduleMap.put("base_user_favorite_shop", "base");
        moduleMap.put("base_website_message", "base");
        moduleMap.put("comment_black_list", "comment");
        moduleMap.put("comment_buyer_score_statistical", "comment");
        moduleMap.put("comment_buyer_to_goods", "comment");
        moduleMap.put("comment_buyer_to_shop", "comment");
        moduleMap.put("comment_goods_score_statistical", "comment");
        moduleMap.put("comment_reply", "comment");
        moduleMap.put("comment_shop_score_statistical", "comment");
        moduleMap.put("comment_shop_to_buyer", "comment");
        moduleMap.put("comment_version", "comment");
        moduleMap.put("commission_every_pay_record", "commission");
        moduleMap.put("commission_shop", "commission");
        moduleMap.put("commission_shop_category_des", "commission");
        moduleMap.put("coupon", "coupon");
        moduleMap.put("coupon_rule", "coupon");
        moduleMap.put("coupon_use", "coupon");
        moduleMap.put("customized_discount", "customized");
        moduleMap.put("customized_discount_item", "customized");
        moduleMap.put("customized_extend_orders", "customized");
        moduleMap.put("customized_page", "customized");
        moduleMap.put("customized_pay_config", "customized");
        moduleMap.put("customized_promotion", "customized");
        moduleMap.put("delivery_addressbase", "delivery");
        moduleMap.put("delivery_company_base", "delivery");
        moduleMap.put("delivery_company_toshop", "delivery");
        moduleMap.put("delivery_express_company", "delivery");
        moduleMap.put("delivery_fee_info", "delivery");
        moduleMap.put("delivery_fee_template", "delivery");
        moduleMap.put("delivery_fee_template_detail", "delivery");
        moduleMap.put("delivery_info", "delivery");
        moduleMap.put("delivery_range", "delivery");
        moduleMap.put("delivery_shop_mapping", "delivery");
        moduleMap.put("delivery_status", "delivery");
        moduleMap.put("delivery_useful_address_info", "delivery");
        moduleMap.put("design_pattern", "design");
        moduleMap.put("distribute_order_interface", "distribute");
        moduleMap.put("ecc_plt_ol_site_d", "ecc");
        moduleMap.put("ecc_plt_ol_site_page_d", "ecc");
        moduleMap.put("ecc_plt_ol_site_page_top10_d", "ecc");
        moduleMap.put("ecc_plt_ol_usertype_d", "ecc");
        moduleMap.put("ecc_shop_ol_site_d", "ecc");
        moduleMap.put("ecc_shop_page_ol_site_d", "ecc");
        moduleMap.put("edition_func", "edition");
        moduleMap.put("field_certification", "field");
        moduleMap.put("field_certification_attachment", "field");
        moduleMap.put("finance_withdraw_apply", "finance");
        moduleMap.put("finance_withdraw_record", "finance");
        moduleMap.put("groupon_info", "groupon");
        moduleMap.put("groupon_order", "groupon");
        moduleMap.put("groupon_rule", "groupon");
        moduleMap.put("item", "item");
        moduleMap.put("item_attr", "item");
        moduleMap.put("item_attr_formula", "item");
        moduleMap.put("item_attr_value", "item");
        moduleMap.put("item_attribute", "item");
        moduleMap.put("item_attribute_value", "item");
        moduleMap.put("item_brand", "item");
        moduleMap.put("item_buyer_extends_info", "item");
        moduleMap.put("item_category", "item");
        moduleMap.put("item_category_attr", "item");
        moduleMap.put("item_category_attr_value", "item");
        moduleMap.put("item_category_bak", "item");
        moduleMap.put("item_category_brand", "item");
        moduleMap.put("item_customized_sku", "item");
        moduleMap.put("item_delivery_info", "item");
        moduleMap.put("item_picpdf", "item");
        moduleMap.put("item_picture", "item");
        moduleMap.put("item_price", "item");
        moduleMap.put("item_sku", "item");
        moduleMap.put("item_sku_picture", "item");
        moduleMap.put("jc_user_info", "jc");
        moduleMap.put("mall_ad_count", "mall");
        moduleMap.put("mall_advertise", "mall");
        moduleMap.put("mall_banner", "mall");
        moduleMap.put("mall_domain_info", "mall");
        moduleMap.put("mall_help_classify", "mall");
        moduleMap.put("mall_help_document", "mall");
        moduleMap.put("mall_info", "mall");
        moduleMap.put("mall_mobile_instance_module", "mall");
        moduleMap.put("mall_mobile_instance_template", "mall");
        moduleMap.put("mall_mobile_publish_template", "mall");
        moduleMap.put("mall_notice", "mall");
        moduleMap.put("mall_recommend", "mall");
        moduleMap.put("mall_recommend_attr", "mall");
        moduleMap.put("mall_tdk", "mall");
        moduleMap.put("mall_user_feedback", "mall");
        moduleMap.put("menu_group", "menu");
        moduleMap.put("menu_resource", "menu");
        moduleMap.put("menu_resource_cancel", "menu");
        moduleMap.put("menu_resource_template", "menu");
        moduleMap.put("mobile_page_config", "mobile");
        moduleMap.put("package_orders", "package");
        moduleMap.put("payment_deal", "payment");
        moduleMap.put("payment_detail", "payment");
        moduleMap.put("payment_mapping", "payment");
        moduleMap.put("plat_account_period_rule", "plat");
        moduleMap.put("platform_activity", "platform");
        moduleMap.put("platform_ad", "platform");
        moduleMap.put("platform_company_info", "platform");
        moduleMap.put("platform_customer_service", "platform");
        moduleMap.put("platform_edition", "platform");
        moduleMap.put("platform_financial_apply", "platform");
        moduleMap.put("platform_financial_apply__data", "platform");
        moduleMap.put("platform_financial_cooperation", "platform");
        moduleMap.put("platform_financial_picture", "platform");
        moduleMap.put("platform_financial_products", "platform");
        moduleMap.put("platform_financial_region", "platform");
        moduleMap.put("platform_front_category", "platform");
        moduleMap.put("platform_front_category_mapping", "platform");
        moduleMap.put("platform_front_editcategory", "platform");
        moduleMap.put("platform_func", "platform");
        moduleMap.put("platform_hotword", "platform");
        moduleMap.put("platform_item", "platform");
        moduleMap.put("platform_item_handbook", "platform");
        moduleMap.put("platform_item_picture", "platform");
        moduleMap.put("platform_item_sku", "platform");
        moduleMap.put("platform_item_sku_picture", "platform");
        moduleMap.put("platform_menu_group_func", "platform");
        moduleMap.put("platform_menu_link", "platform");
        moduleMap.put("platform_recommend_record", "platform");
        moduleMap.put("platform_service_rule", "platform");
        moduleMap.put("platform_user_blacklist", "platform");
        moduleMap.put("promotion_full_reduction", "promotion");
        moduleMap.put("promotion_info", "promotion");
        moduleMap.put("promotion_markdown", "promotion");
        moduleMap.put("promotion_platform", "promotion");
        moduleMap.put("promotion_platform_category", "promotion");
        moduleMap.put("properties_config", "properties");
        moduleMap.put("properties_config_bak", "properties");
        moduleMap.put("properties_template", "properties");
        moduleMap.put("properties_template_bak", "properties");
        moduleMap.put("purchase_order", "purchase");
        moduleMap.put("purchase_order_audit", "purchase");
        moduleMap.put("purchase_product", "purchase");
        moduleMap.put("purchase_quotation_audit", "purchase");
        moduleMap.put("purchase_quote_product", "purchase");
        moduleMap.put("purchase_quote_shop", "purchase");
        moduleMap.put("purchase_vendor", "purchase");
        moduleMap.put("purchase_vendor_invitation", "purchase");
        moduleMap.put("ran_username", "ran");
        moduleMap.put("settlement", "settlement");
        moduleMap.put("settlement_category_expense", "settlement");
        moduleMap.put("settlement_detail", "settlement");
        moduleMap.put("shop_address", "shop");
        moduleMap.put("shop_address_copy", "shop");
        moduleMap.put("shop_banner", "shop");
        moduleMap.put("shop_banner_publish", "shop");
        moduleMap.put("shop_base_layout", "shop");
        moduleMap.put("shop_base_module", "shop");
        moduleMap.put("shop_brand", "shop");
        moduleMap.put("shop_category_seller", "shop");
        moduleMap.put("shop_credit_audit", "shop");
        moduleMap.put("shop_credit_constant_config", "shop");
        moduleMap.put("shop_customer_service", "shop");
        moduleMap.put("shop_distribution_item_sku", "shop");
        moduleMap.put("shop_distributor", "shop");
        moduleMap.put("shop_distributor_rel", "shop");
        moduleMap.put("shop_domain_mapper", "shop");
        moduleMap.put("shop_fare", "shop");
        moduleMap.put("shop_info", "shop");
        moduleMap.put("shop_info_extends", "shop");
        moduleMap.put("shop_info_for_query", "shop");
        moduleMap.put("shop_info_snapshot", "shop");
        moduleMap.put("shop_instance_layout", "shop");
        moduleMap.put("shop_instance_module", "shop");
        moduleMap.put("shop_instance_module_extend", "shop");
        moduleMap.put("shop_instance_page", "shop");
        moduleMap.put("shop_instance_template", "shop");
        moduleMap.put("shop_item_special_rule", "shop");
        moduleMap.put("shop_member", "shop");
        moduleMap.put("shop_member_group", "shop");
        moduleMap.put("shop_member_group_price", "shop");
        moduleMap.put("shop_member_rule", "shop");
        moduleMap.put("shop_platform_category", "shop");
        moduleMap.put("shop_publish_layout", "shop");
        moduleMap.put("shop_publish_module", "shop");
        moduleMap.put("shop_publish_module_extend", "shop");
        moduleMap.put("shop_publish_page", "shop");
        moduleMap.put("shop_publish_template", "shop");
        moduleMap.put("shop_regedit_credit", "shop");
        moduleMap.put("shop_rule", "shop");
        moduleMap.put("shop_sale_template", "shop");
        moduleMap.put("shop_service_rule", "shop");
        moduleMap.put("shop_template", "shop");
        moduleMap.put("shop_template_layout", "shop");
        moduleMap.put("shop_template_module", "shop");
        moduleMap.put("shop_template_page", "shop");
        moduleMap.put("shop_user_check_book", "shop");
        moduleMap.put("shop_user_check_delay", "shop");
        moduleMap.put("shop_user_credit_account", "shop");
        moduleMap.put("shop_user_credit_account_history", "shop");
        moduleMap.put("shop_user_credit_check", "shop");
        moduleMap.put("shop_user_credit_check_batch", "shop");
        moduleMap.put("sms_platform_config", "sms");
        moduleMap.put("sms_task", "sms");
        moduleMap.put("sms_template", "sms");
        moduleMap.put("special_aptitude", "special");
        moduleMap.put("task", "task");
        moduleMap.put("tenant_business_info", "tenant");
        moduleMap.put("tenant_order", "tenant");
        moduleMap.put("tenant_refund", "tenant");
        moduleMap.put("trade_instead_payment", "trade");
        moduleMap.put("trade_inventory", "trade");
        moduleMap.put("trade_inventory_operation_log", "trade");
        moduleMap.put("trade_invoice", "trade");
        moduleMap.put("trade_order_extends_state", "trade");
        moduleMap.put("trade_order_items", "trade");
        moduleMap.put("trade_order_items_price_history", "trade");
        moduleMap.put("trade_order_price_history", "trade");
        moduleMap.put("trade_orders", "trade");
        moduleMap.put("trade_payment_type", "trade");
        moduleMap.put("trade_payment_type_attribute", "trade");
        moduleMap.put("trade_sku_price", "trade");
        moduleMap.put("trade_sku_price_log", "trade");
        moduleMap.put("urp_depart", "urp");
        moduleMap.put("urp_menu", "urp");
        moduleMap.put("urp_menu_group_r", "urp");
        moduleMap.put("urp_menugroup", "urp");
        moduleMap.put("urp_user", "urp");
        moduleMap.put("urp_user_group_r", "urp");
        moduleMap.put("urp_user_menu_r", "urp");
        moduleMap.put("urp_usergroup", "urp");
        moduleMap.put("user", "user");
        moduleMap.put("user_audit", "user");
        moduleMap.put("user_buyer_company_info_device_ky", "user");
        moduleMap.put("user_buyer_company_info_ky", "user");
        moduleMap.put("user_category", "user");
        moduleMap.put("user_contract", "user");
        moduleMap.put("user_contract_audit", "user");
        moduleMap.put("user_extends", "user");
        moduleMap.put("user_mall_resource", "user");
        moduleMap.put("user_mall_resource_template", "user");
        moduleMap.put("user_modify_detail", "user");
        moduleMap.put("user_modify_info", "user");
        moduleMap.put("user_permission", "user");
        moduleMap.put("user_permission_code", "user");
        moduleMap.put("user_permission_code_template", "user");
        moduleMap.put("user_platform_menu", "user");
        moduleMap.put("user_properties", "user");
        moduleMap.put("user_role", "user");
        //===============================================//
        requestMappingMap.put("account_binding_mapping", "account/binding/mapping");
        requestMappingMap.put("after_sale_arbitration", "after/sale/arbitration");
        requestMappingMap.put("after_sale_attachment", "after/sale/attachment");
        requestMappingMap.put("after_sale_audit", "after/sale/audit");
        requestMappingMap.put("after_sale_complaint", "after/sale/complaint");
        requestMappingMap.put("after_sale_evaluation", "after/sale/evaluation");
        requestMappingMap.put("after_sale_refund", "after/sale/refund");
        requestMappingMap.put("after_sale_refund_item", "after/sale/refund/item");
        requestMappingMap.put("after_sale_score_count", "after/sale/score/count");
        requestMappingMap.put("after_sale_service", "after/sale/service");
        requestMappingMap.put("b2b_download_task", "b2b/download/task");
        requestMappingMap.put("b2b_edition", "b2b/edition");
        requestMappingMap.put("b2b_function", "b2b/function");
        requestMappingMap.put("b2b_jsfparam", "b2b/jsfparam");
        requestMappingMap.put("b2b_market_channel", "b2b/market/channel");
        requestMappingMap.put("b2b_module", "b2b/module");
        requestMappingMap.put("base_flow", "base/flow");
        requestMappingMap.put("base_msg_record", "base/msg/record");
        requestMappingMap.put("base_sms_config", "base/sms/config");
        requestMappingMap.put("base_user_favorite_item", "base/user/favorite/item");
        requestMappingMap.put("base_user_favorite_shop", "base/user/favorite/shop");
        requestMappingMap.put("base_website_message", "base/website/message");
        requestMappingMap.put("comment_black_list", "comment/black/list");
        requestMappingMap.put("comment_buyer_score_statistical", "comment/buyer/score/statistical");
        requestMappingMap.put("comment_buyer_to_goods", "comment/buyer/to/goods");
        requestMappingMap.put("comment_buyer_to_shop", "comment/buyer/to/shop");
        requestMappingMap.put("comment_goods_score_statistical", "comment/goods/score/statistical");
        requestMappingMap.put("comment_reply", "comment/reply");
        requestMappingMap.put("comment_shop_score_statistical", "comment/shop/score/statistical");
        requestMappingMap.put("comment_shop_to_buyer", "comment/shop/to/buyer");
        requestMappingMap.put("comment_version", "comment/version");
        requestMappingMap.put("commission_every_pay_record", "commission/every/pay/record");
        requestMappingMap.put("commission_shop", "commission/shop");
        requestMappingMap.put("commission_shop_category_des", "commission/shop/category/des");
        requestMappingMap.put("coupon", "coupon");
        requestMappingMap.put("coupon_rule", "coupon/rule");
        requestMappingMap.put("coupon_use", "coupon/use");
        requestMappingMap.put("customized_discount", "customized/discount");
        requestMappingMap.put("customized_discount_item", "customized/discount/item");
        requestMappingMap.put("customized_extend_orders", "customized/extend/orders");
        requestMappingMap.put("customized_page", "customized/page");
        requestMappingMap.put("customized_pay_config", "customized/pay/config");
        requestMappingMap.put("customized_promotion", "customized/promotion");
        requestMappingMap.put("delivery_addressbase", "delivery/addressbase");
        requestMappingMap.put("delivery_company_base", "delivery/company/base");
        requestMappingMap.put("delivery_company_toshop", "delivery/company/toshop");
        requestMappingMap.put("delivery_express_company", "delivery/express/company");
        requestMappingMap.put("delivery_fee_info", "delivery/fee/info");
        requestMappingMap.put("delivery_fee_template", "delivery/fee/template");
        requestMappingMap.put("delivery_fee_template_detail", "delivery/fee/template/detail");
        requestMappingMap.put("delivery_info", "delivery/info");
        requestMappingMap.put("delivery_range", "delivery/range");
        requestMappingMap.put("delivery_shop_mapping", "delivery/shop/mapping");
        requestMappingMap.put("delivery_status", "delivery/status");
        requestMappingMap.put("delivery_useful_address_info", "delivery/useful/address/info");
        requestMappingMap.put("design_pattern", "design/pattern");
        requestMappingMap.put("distribute_order_interface", "distribute/order/interface");
        requestMappingMap.put("ecc_plt_ol_site_d", "ecc/plt/ol/site/d");
        requestMappingMap.put("ecc_plt_ol_site_page_d", "ecc/plt/ol/site/page/d");
        requestMappingMap.put("ecc_plt_ol_site_page_top10_d", "ecc/plt/ol/site/page/top10/d");
        requestMappingMap.put("ecc_plt_ol_usertype_d", "ecc/plt/ol/usertype/d");
        requestMappingMap.put("ecc_shop_ol_site_d", "ecc/shop/ol/site/d");
        requestMappingMap.put("ecc_shop_page_ol_site_d", "ecc/shop/page/ol/site/d");
        requestMappingMap.put("edition_func", "edition/func");
        requestMappingMap.put("field_certification", "field/certification");
        requestMappingMap.put("field_certification_attachment", "field/certification/attachment");
        requestMappingMap.put("finance_withdraw_apply", "finance/withdraw/apply");
        requestMappingMap.put("finance_withdraw_record", "finance/withdraw/record");
        requestMappingMap.put("groupon_info", "groupon/info");
        requestMappingMap.put("groupon_order", "groupon/order");
        requestMappingMap.put("groupon_rule", "groupon/rule");
        requestMappingMap.put("item", "item");
        requestMappingMap.put("item_attr", "item/attr");
        requestMappingMap.put("item_attr_formula", "item/attr/formula");
        requestMappingMap.put("item_attr_value", "item/attr/value");
        requestMappingMap.put("item_attribute", "item/attribute");
        requestMappingMap.put("item_attribute_value", "item/attribute/value");
        requestMappingMap.put("item_brand", "item/brand");
        requestMappingMap.put("item_buyer_extends_info", "item/buyer/extends/info");
        requestMappingMap.put("item_category", "item/category");
        requestMappingMap.put("item_category_attr", "item/category/attr");
        requestMappingMap.put("item_category_attr_value", "item/category/attr/value");
        requestMappingMap.put("item_category_bak", "item/category/bak");
        requestMappingMap.put("item_category_brand", "item/category/brand");
        requestMappingMap.put("item_customized_sku", "item/customized/sku");
        requestMappingMap.put("item_delivery_info", "item/delivery/info");
        requestMappingMap.put("item_picpdf", "item/picpdf");
        requestMappingMap.put("item_picture", "item/picture");
        requestMappingMap.put("item_price", "item/price");
        requestMappingMap.put("item_sku", "item/sku");
        requestMappingMap.put("item_sku_picture", "item/sku/picture");
        requestMappingMap.put("jc_user_info", "jc/user/info");
        requestMappingMap.put("mall_ad_count", "mall/ad/count");
        requestMappingMap.put("mall_advertise", "mall/advertise");
        requestMappingMap.put("mall_banner", "mall/banner");
        requestMappingMap.put("mall_domain_info", "mall/domain/info");
        requestMappingMap.put("mall_help_classify", "mall/help/classify");
        requestMappingMap.put("mall_help_document", "mall/help/document");
        requestMappingMap.put("mall_info", "mall/info");
        requestMappingMap.put("mall_mobile_instance_module", "mall/mobile/instance/module");
        requestMappingMap.put("mall_mobile_instance_template", "mall/mobile/instance/template");
        requestMappingMap.put("mall_mobile_publish_template", "mall/mobile/publish/template");
        requestMappingMap.put("mall_notice", "mall/notice");
        requestMappingMap.put("mall_recommend", "mall/recommend");
        requestMappingMap.put("mall_recommend_attr", "mall/recommend/attr");
        requestMappingMap.put("mall_tdk", "mall/tdk");
        requestMappingMap.put("mall_user_feedback", "mall/user/feedback");
        requestMappingMap.put("menu_group", "menu/group");
        requestMappingMap.put("menu_resource", "menu/resource");
        requestMappingMap.put("menu_resource_cancel", "menu/resource/cancel");
        requestMappingMap.put("menu_resource_template", "menu/resource/template");
        requestMappingMap.put("mobile_page_config", "mobile/page/config");
        requestMappingMap.put("package_orders", "package/orders");
        requestMappingMap.put("payment_deal", "payment/deal");
        requestMappingMap.put("payment_detail", "payment/detail");
        requestMappingMap.put("payment_mapping", "payment/mapping");
        requestMappingMap.put("plat_account_period_rule", "plat/account/period/rule");
        requestMappingMap.put("platform_activity", "platform/activity");
        requestMappingMap.put("platform_ad", "platform/ad");
        requestMappingMap.put("platform_company_info", "platform/company/info");
        requestMappingMap.put("platform_customer_service", "platform/customer/service");
        requestMappingMap.put("platform_edition", "platform/edition");
        requestMappingMap.put("platform_financial_apply", "platform/financial/apply");
        requestMappingMap.put("platform_financial_apply__data", "platform/financial/apply//data");
        requestMappingMap.put("platform_financial_cooperation", "platform/financial/cooperation");
        requestMappingMap.put("platform_financial_picture", "platform/financial/picture");
        requestMappingMap.put("platform_financial_products", "platform/financial/products");
        requestMappingMap.put("platform_financial_region", "platform/financial/region");
        requestMappingMap.put("platform_front_category", "platform/front/category");
        requestMappingMap.put("platform_front_category_mapping", "platform/front/category/mapping");
        requestMappingMap.put("platform_front_editcategory", "platform/front/editcategory");
        requestMappingMap.put("platform_func", "platform/func");
        requestMappingMap.put("platform_hotword", "platform/hotword");
        requestMappingMap.put("platform_item", "platform/item");
        requestMappingMap.put("platform_item_handbook", "platform/item/handbook");
        requestMappingMap.put("platform_item_picture", "platform/item/picture");
        requestMappingMap.put("platform_item_sku", "platform/item/sku");
        requestMappingMap.put("platform_item_sku_picture", "platform/item/sku/picture");
        requestMappingMap.put("platform_menu_group_func", "platform/menu/group/func");
        requestMappingMap.put("platform_menu_link", "platform/menu/link");
        requestMappingMap.put("platform_recommend_record", "platform/recommend/record");
        requestMappingMap.put("platform_service_rule", "platform/service/rule");
        requestMappingMap.put("platform_user_blacklist", "platform/user/blacklist");
        requestMappingMap.put("promotion_full_reduction", "promotion/full/reduction");
        requestMappingMap.put("promotion_info", "promotion/info");
        requestMappingMap.put("promotion_markdown", "promotion/markdown");
        requestMappingMap.put("promotion_platform", "promotion/platform");
        requestMappingMap.put("promotion_platform_category", "promotion/platform/category");
        requestMappingMap.put("properties_config", "properties/config");
        requestMappingMap.put("properties_config_bak", "properties/config/bak");
        requestMappingMap.put("properties_template", "properties/template");
        requestMappingMap.put("properties_template_bak", "properties/template/bak");
        requestMappingMap.put("purchase_order", "purchase/order");
        requestMappingMap.put("purchase_order_audit", "purchase/order/audit");
        requestMappingMap.put("purchase_product", "purchase/product");
        requestMappingMap.put("purchase_quotation_audit", "purchase/quotation/audit");
        requestMappingMap.put("purchase_quote_product", "purchase/quote/product");
        requestMappingMap.put("purchase_quote_shop", "purchase/quote/shop");
        requestMappingMap.put("purchase_vendor", "purchase/vendor");
        requestMappingMap.put("purchase_vendor_invitation", "purchase/vendor/invitation");
        requestMappingMap.put("ran_username", "ran/username");
        requestMappingMap.put("settlement", "settlement");
        requestMappingMap.put("settlement_category_expense", "settlement/category/expense");
        requestMappingMap.put("settlement_detail", "settlement/detail");
        requestMappingMap.put("shop_address", "shop/address");
        requestMappingMap.put("shop_address_copy", "shop/address/copy");
        requestMappingMap.put("shop_banner", "shop/banner");
        requestMappingMap.put("shop_banner_publish", "shop/banner/publish");
        requestMappingMap.put("shop_base_layout", "shop/base/layout");
        requestMappingMap.put("shop_base_module", "shop/base/module");
        requestMappingMap.put("shop_brand", "shop/brand");
        requestMappingMap.put("shop_category_seller", "shop/category/seller");
        requestMappingMap.put("shop_credit_audit", "shop/credit/audit");
        requestMappingMap.put("shop_credit_constant_config", "shop/credit/constant/config");
        requestMappingMap.put("shop_customer_service", "shop/customer/service");
        requestMappingMap.put("shop_distribution_item_sku", "shop/distribution/item/sku");
        requestMappingMap.put("shop_distributor", "shop/distributor");
        requestMappingMap.put("shop_distributor_rel", "shop/distributor/rel");
        requestMappingMap.put("shop_domain_mapper", "shop/domain/mapper");
        requestMappingMap.put("shop_fare", "shop/fare");
        requestMappingMap.put("shop_info", "shop/info");
        requestMappingMap.put("shop_info_extends", "shop/info/extends");
        requestMappingMap.put("shop_info_for_query", "shop/info/for/query");
        requestMappingMap.put("shop_info_snapshot", "shop/info/snapshot");
        requestMappingMap.put("shop_instance_layout", "shop/instance/layout");
        requestMappingMap.put("shop_instance_module", "shop/instance/module");
        requestMappingMap.put("shop_instance_module_extend", "shop/instance/module/extend");
        requestMappingMap.put("shop_instance_page", "shop/instance/page");
        requestMappingMap.put("shop_instance_template", "shop/instance/template");
        requestMappingMap.put("shop_item_special_rule", "shop/item/special/rule");
        requestMappingMap.put("shop_member", "shop/member");
        requestMappingMap.put("shop_member_group", "shop/member/group");
        requestMappingMap.put("shop_member_group_price", "shop/member/group/price");
        requestMappingMap.put("shop_member_rule", "shop/member/rule");
        requestMappingMap.put("shop_platform_category", "shop/platform/category");
        requestMappingMap.put("shop_publish_layout", "shop/publish/layout");
        requestMappingMap.put("shop_publish_module", "shop/publish/module");
        requestMappingMap.put("shop_publish_module_extend", "shop/publish/module/extend");
        requestMappingMap.put("shop_publish_page", "shop/publish/page");
        requestMappingMap.put("shop_publish_template", "shop/publish/template");
        requestMappingMap.put("shop_regedit_credit", "shop/regedit/credit");
        requestMappingMap.put("shop_rule", "shop/rule");
        requestMappingMap.put("shop_sale_template", "shop/sale/template");
        requestMappingMap.put("shop_service_rule", "shop/service/rule");
        requestMappingMap.put("shop_template", "shop/template");
        requestMappingMap.put("shop_template_layout", "shop/template/layout");
        requestMappingMap.put("shop_template_module", "shop/template/module");
        requestMappingMap.put("shop_template_page", "shop/template/page");
        requestMappingMap.put("shop_user_check_book", "shop/user/check/book");
        requestMappingMap.put("shop_user_check_delay", "shop/user/check/delay");
        requestMappingMap.put("shop_user_credit_account", "shop/user/credit/account");
        requestMappingMap.put("shop_user_credit_account_history", "shop/user/credit/account/history");
        requestMappingMap.put("shop_user_credit_check", "shop/user/credit/check");
        requestMappingMap.put("shop_user_credit_check_batch", "shop/user/credit/check/batch");
        requestMappingMap.put("sms_platform_config", "sms/platform/config");
        requestMappingMap.put("sms_task", "sms/task");
        requestMappingMap.put("sms_template", "sms/template");
        requestMappingMap.put("special_aptitude", "special/aptitude");
        requestMappingMap.put("task", "task");
        requestMappingMap.put("tenant_business_info", "tenant/business/info");
        requestMappingMap.put("tenant_order", "tenant/order");
        requestMappingMap.put("tenant_refund", "tenant/refund");
        requestMappingMap.put("trade_instead_payment", "trade/instead/payment");
        requestMappingMap.put("trade_inventory", "trade/inventory");
        requestMappingMap.put("trade_inventory_operation_log", "trade/inventory/operation/log");
        requestMappingMap.put("trade_invoice", "trade/invoice");
        requestMappingMap.put("trade_order_extends_state", "trade/order/extends/state");
        requestMappingMap.put("trade_order_items", "trade/order/items");
        requestMappingMap.put("trade_order_items_price_history", "trade/order/items/price/history");
        requestMappingMap.put("trade_order_price_history", "trade/order/price/history");
        requestMappingMap.put("trade_orders", "trade/orders");
        requestMappingMap.put("trade_payment_type", "trade/payment/type");
        requestMappingMap.put("trade_payment_type_attribute", "trade/payment/type/attribute");
        requestMappingMap.put("trade_sku_price", "trade/sku/price");
        requestMappingMap.put("trade_sku_price_log", "trade/sku/price/log");
        requestMappingMap.put("urp_depart", "urp/depart");
        requestMappingMap.put("urp_menu", "urp/menu");
        requestMappingMap.put("urp_menu_group_r", "urp/menu/group/r");
        requestMappingMap.put("urp_menugroup", "urp/menugroup");
        requestMappingMap.put("urp_user", "urp/user");
        requestMappingMap.put("urp_user_group_r", "urp/user/group/r");
        requestMappingMap.put("urp_user_menu_r", "urp/user/menu/r");
        requestMappingMap.put("urp_usergroup", "urp/usergroup");
        requestMappingMap.put("user", "user");
        requestMappingMap.put("user_audit", "user/audit");
        requestMappingMap.put("user_buyer_company_info_device_ky", "user/buyer/company/info/device/ky");
        requestMappingMap.put("user_buyer_company_info_ky", "user/buyer/company/info/ky");
        requestMappingMap.put("user_category", "user/category");
        requestMappingMap.put("user_contract", "user/contract");
        requestMappingMap.put("user_contract_audit", "user/contract/audit");
        requestMappingMap.put("user_extends", "user/extends");
        requestMappingMap.put("user_mall_resource", "user/mall/resource");
        requestMappingMap.put("user_mall_resource_template", "user/mall/resource/template");
        requestMappingMap.put("user_modify_detail", "user/modify/detail");
        requestMappingMap.put("user_modify_info", "user/modify/info");
        requestMappingMap.put("user_permission", "user/permission");
        requestMappingMap.put("user_permission_code", "user/permission/code");
        requestMappingMap.put("user_permission_code_template", "user/permission/code/template");
        requestMappingMap.put("user_platform_menu", "user/platform/menu");
        requestMappingMap.put("user_properties", "user/properties");
        requestMappingMap.put("user_role", "user/role");
    }


    public static void main(String[] args){
        char fieldSeparator = PropUtils.getPorp("fieldSeparator").toCharArray()[0];
        System.out.println("    //===============================================//");
        GenerateNeedMap.printTableNameToPojoMap("needTablesMap",fieldSeparator);
        System.out.println("    //===============================================//");
        GenerateNeedMap.printTableNamesMap("needTablesList",fieldSeparator);
        System.out.println("    //===============================================//");
        GenerateNeedMap.printTableNameToModuleMap("moduleMap",fieldSeparator);
        System.out.println("    //===============================================//");
        GenerateNeedMap.printRequestMappingMap("requestMappingMap",fieldSeparator);
    }

}
